### PR TITLE
Update dependencies and run action on PRs to test main entrypoint

### PR DESCRIPTION
**Pull request by mathieu1**
All recent versions of the action seem broken to me, and this PR fixes that. Moreover it achieves the following items:

- [x] Use latest version of actions-toolkit to avoid ending up with unstable octokit-next dependencies.
    - [x] `toolkit.config` is replaced with loading the config file with `js-yaml`
- [x] Support `pull_request.opened`, `pull_request.reopened`, `pull_request.labeled` and `pull_request.unlabeled`events, as well as all `pull_request_target` equivalents.
- [x] Apply action to its own repository.
    - [x] In particular, on each PR synchronization, this action is run in its current state.
    - [x] This is a cheap way to fix https://github.com/travelperk/label-requires-reviews-action/issues/2, even though it's not part of the test suite.

Screenshot 2023-02-18 at 23 16 16

### CODE REVIEW

**Comment by namelivia** [comment]
> All recent versions of the action seem broken to me
First, thank you for your help.
Please, could you please elaborate a little bit on this? What errors did you get? Which versions?
Thanks!

**Comment by mathieu1** [comment]
> > All recent versions of the action seem broken to me
> 
> Please, could you please elaborate a little bit on this? What errors did you get? Which versions? Thanks!

Sure, have a look at the tests on https://github.com/mathieu1/label-requires-reviews-action/pull/5 :

- Version 1.0.1: works fine
- Commit `ee3e82e32650be13bc075ee00bbf5ff95bfc01cd` (before my first PR): SyntaxError
```
Run travelperk/label-requires-reviews-action@ee3e82e32650be13bc075ee00bbf5ff95bfc01cd
/home/runner/work/_actions/travelperk/label-requires-reviews-action/ee3e82e32650be13bc075ee00bbf5ff95bfc01cd/dist/index.js:27214
  const log = requestOptions.request?.log || console;
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
- Version `1.2.0`: same SyntaxError
```
Run travelperk/label-requires-reviews-action@1.2.0
/home/runner/work/_actions/travelperk/label-requires-reviews-action/1.2.0/dist/index.js:27225
  const log = requestOptions.request?.log || console;
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
- Version `mathieu1:feat/apply-self` (my new PR): works fine.

These Syntax errors can be reproduced simply by running `npm dist/index.js` on the relevant versions.

**Comment by mathieu1** [comment]
I actually haven't gotten to the bottom of why these syntax errors occur, but I just found a sensible set of dependencies for which they don't happen. And with the new check included in this PR, it's very easy to see while working on a PR whenever the syntax errors pop up again

**Comment by namelivia** [comment]
Sorry, I'll review it asap

**Review by namelivia — APPROVED** [review]
Lgtm! Thank you!

**Comment by namelivia** [comment]
Applied on: https://github.com/travelperk/label-requires-reviews-action/releases/tag/1.2.1

**Pull request merged**
